name: Build CV

on:
  pull_request:
    branches:
      - TEMP_DO_NOT_RUN
  push:
    branches:
      - TEMP_DO_NOT_RUN
    paths:
      - 'src/cv/cv.yaml'
      - 'src/cv/cv.html.tmpl'
      - 'src/static/cv.css'

jobs:
  build-and-deploy-cv:
    name: Build and deploy CV
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
    - name: Generate CV from YAML
      run: |
          pip3 install -r scripts/requirements.txt
          python3 scripts/generate_cv.py -c src/cv/cv.yaml -t src/cv/cv.html.tmpl -o cv.html
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ":sparkles: CV Updates"
