name: Build Website

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - 'src/markdown/**.md'
      - 'src/static/website.css'
      - 'src/main.go'

jobs:
  build-and-deploy-website:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Generate website
      run: |
          cd src
          go mod tidy
          go run main.go --static ..
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ":sparkles: Website Updates"
