name: Build Website

on:
  push:
    branches:
      - master
    paths:
      - 'markdown/**.md'
      - 'templates/**'
      - '!/templates/cv.html.tmpl'

jobs:
  build-and-deploy-website:
    name: Build and deploy website
    uses: joshjennings98/joshjennings98.github.io/.github/workflows/update.yml@master
    secrets:
      GIT_SECRET: ${{ secrets.GITHUB_TOKEN }}
    with:
      update: website
      branch: ${{ github.head_ref || github.ref }}
