name: Build CV

on:
  push:
    branches:
      - master
    paths:
      - 'files/src/cv.yaml'
      - 'files/templates/cv.html.template'

jobs:
  build-and-deploy-cv:
    name: Build and deploy CV
    uses: joshjennings98/joshjennings98.github.io/.github/workflows/update.yml@master
    secrets:
      GIT_SECRET: ${{ secrets.GITHUB_TOKEN }}
    with:
      update: cv
      branch: ${{ github.head_ref || github.ref }}
