name: Build CV

on:
  push:
    branches:
      - masterTEMPDONOTRUN
    paths:
      - 'src/cv.yaml'
      - 'src/cv.css'
      - 'src/cv.html.tmpl'

jobs:
  build-and-deploy-cv:
    name: Build and deploy CV
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
    - name: Generate CV from YAML
      run: |
          pip3 install -r requirements.txt
          python3 scripts/generate_cv.py -c src/cv.yaml -t src/cv.html.tmpl -o CV-Josh-Jennings.html
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ":sparkles: CV Updates"
